_target_: src.models.UnetModule.Unet
lr: 0.0001
optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 500

net:
  _target_:  monai.networks.nets.UNet
  spatial_dims: 3
  in_channels: 1
  channels:
    - 32
    - 64
    - 128
    - 256
    - 512
  out_channels: 8
  kernel_size: 3
  up_kernel_size: 3
  num_res_units: 0
  act: leakyrelu
  norm: 'instance'
  dropout: 0.1
  strides:
    - 2
    - 2
    - 2
    - 2
# compile model for faster training with pytorch 2.0
compile: false